---
extends: "default"
ignore: |
  /nautobot_circuit_maintenance/fixtures/

rules:
  comments: "enable"
  empty-values: "enable"
  indentation:
    indent-sequences: "consistent"
  line-length: "disable"
  quoted-strings:
    quote-type: "double"
